In [2]:
import numpy
print("numpy::",numpy.__version__)
import pandas
print("pandas::",pandas.__version__)

numpy:: 1.19.2
pandas:: 1.1.3


In [3]:
import numpy as np

In [4]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [7]:
np.amin(a)

0

In [8]:
np.amin(a,1)

array([0, 2])

In [9]:
np.amax(a,0)

array([2, 3])

In [10]:
np.amax(a,axis=0)

array([2, 3])

In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('our array is:')

our array is:


In [15]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print("applying amin() function :rowwise")
print(np.amin(a,axis=1))
print('\n')
print(np.amin(a,1))

applying amin() function :rowwise
[1 4 7]


[1 4 7]


In [21]:
print("Applying amin() function again:column wise")
print(np.amin(a,0))

Applying amin() function again:column wise
[1 2 3]


In [22]:
print("Applying amax() function: rowwise")
print(np.amax(a,1))

Applying amax() function: rowwise
[3 6 9]


In [23]:
#peek to peek operation=maximum-minimum(np.ptp)
a=np.array([[5,1,4],[8,2,0],[7,3,6]])
print("our array is:")
print(a)

our array is:
[[5 1 4]
 [8 2 0]
 [7 3 6]]


In [24]:
print("Applying ptp() function:")
print(np.ptp(a))

Applying ptp() function:
8


In [25]:
print("Applying ptp() function :row wise")
print(np.ptp(a,axis=1))

Applying ptp() function :row wise
[4 8 4]


In [26]:
print("Applying ptp() function :column wise")
print(np.ptp(a,axis=0))

Applying ptp() function :column wise
[3 2 6]


In [27]:
np.shape(a)

(3, 3)

In [33]:
a

array([[5, 1, 4],
       [8, 2, 0],
       [7, 3, 6]])

In [29]:
np.median(a)

4.0

In [30]:
np.median(a,0)

array([7., 2., 4.])

In [31]:
np.mean(a)

4.0

In [32]:
np.mean(a,0)

array([6.66666667, 2.        , 3.33333333])

In [34]:
np.mean(a,1)

array([3.33333333, 3.33333333, 5.33333333])

In [35]:
g=np.array([[2,4,3],[7,8,9]])
g

array([[2, 4, 3],
       [7, 8, 9]])

In [36]:
g.shape

(2, 3)

In [37]:
g.reshape(3,2)

array([[2, 4],
       [3, 7],
       [8, 9]])

In [39]:
g.min()

2

In [40]:
g.max()

9

In [41]:
g.size

6

In [42]:
g.itemsize

4

In [43]:
g.dtype

dtype('int32')

In [44]:
g.data

In [55]:
a=np.array([[1,2],[3,4],[5,6]], dtype='float')
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [56]:
a.itemsize

8

In [47]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [48]:
print(x)

[0 1 2 3 4]


In [49]:
x=np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [51]:
x.ndim

2

In [52]:
type(x)

numpy.ndarray

In [57]:
x.ravel()

array([0, 1, 2, 3, 4, 5])

In [58]:
print(x.ravel())

[0 1 2 3 4 5]


In [65]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [66]:
b=np.arange(4)

In [67]:
print(b)

[0 1 2 3]


In [68]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [69]:
print(b**2)

[0 1 4 9]


In [70]:
d1=np.arange(20)
s=slice(2,20,2)
print(d1[s])

[ 2  4  6  8 10 12 14 16 18]


In [71]:
d1[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
d2=np.array([np.nan,1,2,3,np.nan,6,7,8])
d2

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [75]:
print(d2[~np.isnan(d2)])

[1. 2. 3. 6. 7. 8.]


In [76]:
import pandas as pd
import numpy as np

In [78]:
a=pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [79]:
a=pd.Series([1,2,3,4],index=[100,101,102,103])
a

100    1
101    2
102    3
103    4
dtype: int64

In [80]:
a=pd.Series([1,2,3],index=[10,11,12],dtype=float)
a

10    1.0
11    2.0
12    3.0
dtype: float64

In [82]:
s=pd.Series([20,34,39,42,59])
print(s[0])

20


In [83]:
s[3]

42

In [85]:
s=pd.Series([10,20,30,40,50,60,70,80])
(s[0:3])

0    10
1    20
2    30
dtype: int64

In [87]:
data=np.array([1,2,3,4])
m=pd.Series(data)
m

0    1
1    2
2    3
3    4
dtype: int32

In [89]:
demodict={'name':'X','Age':12}
s1=pd.Series(demodict)
s1

name     X
Age     12
dtype: object

In [91]:
ckr={'name':'Virat','runs':243,'innings':3,'balls':56}
s2=pd.Series(ckr)
s2

name       Virat
runs         243
innings        3
balls         56
dtype: object

In [92]:
"India"+"my"+"country"

'Indiamycountry'

In [93]:
"India "+" my "+" country"

'India  my  country'

In [94]:
"India "+"my"+" country"

'India my country'

In [97]:
x=["ab","cd"]
for i in x:
    i.upper()
    print(x)

['ab', 'cd']
['ab', 'cd']


In [104]:
x=['ab,cd']
x.upper()

AttributeError: 'list' object has no attribute 'upper'

In [105]:
import pandas as pd

In [106]:
data=[1,2,3,4]
df=pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4

In [107]:
data=[['Alex',10],['Mouni',14],['Sri',15]]
df=pd.DataFrame(data,index=[100,101,102],columns=['Name','Age'],dtype=float)
df

Name   Age
100   Alex  10.0
101  Mouni  14.0
102    Sri  15.0

In [108]:
data={'Name':['MOuni','Sri','Naina','kranthi'],'Age':[28,34,29,42]}
df=pd.DataFrame(data)
df

Name  Age
0    MOuni   28
1      Sri   34
2    Naina   29
3  kranthi   42

In [112]:
pd.DataFrame(data,index=['First','Second','Third','Fourth'],dtype=float)


Name   Age
First     MOuni  28.0
Second      Sri  34.0
Third     Naina  29.0
Fourth  kranthi  42.0

In [113]:
df=pd.DataFrame(np.random.randn(8,4),columns=['A','B','C','D'])
print(df)

          A         B         C         D
0  1.025891  0.647458  0.156613 -0.664578
1 -1.683147 -0.954056 -0.632442  1.475370
2  0.468370 -0.844319 -0.200846  2.473042
3  0.416368 -1.328269 -0.665638 -0.371164
4 -0.434403  1.031630 -0.032918  0.006939
5 -0.060597  0.778947  0.557455 -0.466757
6 -0.578744 -0.060336 -0.009198 -0.162141
7  0.341028 -0.430122  1.067796 -0.218518


In [114]:
print(df.iloc[2:3,-4:])

         A         B         C         D
2  0.46837 -0.844319 -0.200846  2.473042
